<a href="https://colab.research.google.com/github/juancmq/stats2023/blob/main/Juan_Monsalve_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [37]:
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [38]:
for i in range(5,8): # this will display these range of numbers minus 1
    print(i)

5
6
7


In [39]:
for i in range(3):
    print( "Test Number: " , i ) # this will display the number next to the text you wrote

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [40]:
def square(x):
    return x**2 #this defines what you want it to do when you type square, remember ** is to the power of

In [41]:
square(5)

25

In [42]:
square(square(2)) #you can also square a square when you define the function

16

In [43]:
square(square(square(2))) # you can square as many times as you'd like


256

In [44]:
square(123456)

15241383936

In [45]:
square(square(5))

625

In [46]:
def add_two(x): #you can pretty much define any function as anything you want
    return x+2

In [47]:
add_two(5)

7

In [48]:
square(add_two(5)) # we do this everytime we want to do the function twice

49

### Logical Branching

In [49]:
choice = "apple"

In [50]:
if choice == "apple":

    print("You choose apples.") #with this function you can display something specfic depending on the choice of the person

else:
    
    print("You did not choose apples.")

You choose apples.


In [51]:
choice = "orange"

In [52]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [53]:
choice = "apple"

In [54]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!") # you can combine all these functions to display a range of different texts

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [59]:
choice = input("Please enter your choice (i.e. apple): ") # with this function you are able to give a choice in order for there to be a display

Please enter your choice (i.e. apple): kiwi


In [60]:
choice # this goes with the prevoius function displaying your choice

'kiwi'

In [61]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges": #elif can be used to type an extra option

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You did not choose apples or oranges.


#### Coins

In [63]:
import numpy as np

In [65]:
np.random.random() #this will give you a random number between 0 and 1

0.36760624799124386

In [68]:
np.random.random() > 0.5 # this function can tell you whether the random number is higher or lower than a specific amount

True

In [70]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads") # in this case we are creating a coin flip by assigning head and tails to certain numbers
    else:
        print("Tails")

In [71]:
flip_coin()

Heads


### Graphics Output

In [72]:
from IPython.core.display import display, HTML

In [74]:
display(HTML('<h1>Hello, world!</h1>')) #this will diplay any text you'd like in a bold font

In [75]:
def coin():
  return np.random.randint(2)

In [76]:
coin()

0

In [78]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) # this is the image we will use to display when the coin flips heads

In [80]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' #this is how we define words with images

In [81]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [83]:
show_img(heads) #this displays the image in the link

In [84]:
show_img(tails)

In [86]:
def flip_coin():

    if coin():
        show_img(heads)  #here this command will display the heads or tails image randomly
    else:
        show_img(tails)

In [87]:
flip_coin()

In [90]:
for i in range(5): # with this command we can flip the coin multiple times at once
    flip_coin()

In [91]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [92]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [95]:
a = np.arange(52) #this function will give us the numbers 0 to 51

In [96]:
shuffle(a) # with the first function this will shuffle the numbers randomly

array([36, 10, 47, 19, 37, 50, 41, 35,  4, 51, 31, 42, 48,  5, 21, 17, 13,
       12, 39,  1, 38, 11, 20, 49, 30, 45, 22,  0, 18,  8,  7, 32, 26, 40,
       29, 27,  3, 44,  2, 34, 23,  9, 15, 16,  6, 14, 33, 46, 43, 25, 28,
       24])

In [98]:
np.random.permutation(52)

array([30,  1, 45, 12, 24, 46, 41, 21, 42, 16,  0, 43, 35, 10,  2,  3, 29,
       14,  7, 19,  6, 13, 23,  8, 37, 38, 44, 32, 50, 49, 15, 48,  9, 22,
       39, 31, 40, 17,  5, 11, 28, 33, 26, 47, 34, 18,  4, 51, 25, 20, 27,
       36])

### Speed Test

In [99]:
%%timeit
shuffle(a)

167 µs ± 3.55 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [100]:
%%timeit
np.random.permutation(52)

3.66 µs ± 169 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [101]:
import numpy as np

In [102]:
np.random.permutation(52)

array([ 8, 16, 28,  6, 46, 49, 22, 23, 13, 30, 50, 27, 25, 34, 51, 42, 19,
       44,  2, 21, 14, 17, 47,  7,  3, 41, 35,  4, 24, 32, 11, 38,  1, 45,
       29, 36, 31, 12, 10, 18, 39, 15, 48, 40, 43, 26, 37,  0,  9, 20, 33,
        5])

In [104]:
cards = np.random.permutation(52) # in this case we can make a card game assigning each card to a number and displaying them randomly

In [105]:
cards

array([21, 10, 47, 31, 39, 30, 13,  2, 37, 36, 44,  1, 45, 27, 38,  4, 16,
       29, 49, 15,  0, 28, 11, 17, 43, 41, 34,  9, 26, 46, 51,  6, 50, 40,
       20, 42,  8, 14, 12, 33,  5, 35, 32, 48, 18,  3, 25, 22, 19, 23,  7,
       24])

In [112]:
cards[0] # the number inside the parenthesis is which number it will chose from block above

21

In [110]:
cards[1]

10

In [111]:
cards[2]

47

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [113]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [114]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [115]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [118]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #here we are defining the different cards

In [120]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit] #this function will make it return to us as a combination of the names of the previous function

In [123]:
card_name(0) # again number in parenthesis is which one we want to display with text

'Ace of Clubs'

In [124]:
card_name(51)

'King of Diamonds'

In [125]:
cards = np.random.permutation(52)

In [128]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1]) #here we are giving more definitions in order to make the game of cards

In [127]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Four of Spades', 'Two of Hearts', 'Nine of Hearts')

In [130]:
for i in range(5):
    print(card_name(cards[i])) #this will give you five names of cards at the same time

Four of Spades
Two of Hearts
Jack of Diamonds
Ace of Clubs
Two of Spades


In [131]:
for i in range(15):
    print(card_name(cards[i]))

Four of Spades
Two of Hearts
Jack of Diamonds
Ace of Clubs
Two of Spades
Five of Clubs
Five of Spades
Three of Clubs
Four of Clubs
Eight of Spades
Jack of Clubs
Ten of Diamonds
Ten of Clubs
Seven of Spades
Five of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [135]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" #here we are giving the cards images instead of names
card_url_tail = ".png"

In [136]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [137]:
i = np.random.randint(4)
j = np.random.randint(13)

In [138]:
i,j

(3, 10)

In [139]:
suit[i]

'l'

In [140]:
card[j]

'j'

In [141]:
from IPython.core.display import display, HTML

In [142]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [147]:
img = card_url_head + suit[i] + card[j] + card_url_tail #this combines the images and the cards

In [145]:
show_img(img) #this is how the cards will be displayed

In [148]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [149]:
card_image(3)

'k4'

In [150]:
img = card_url_head + card_image(3) + card_url_tail

In [151]:
show_img(img)

In [153]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img) # these are all the cards that will be displayed